DELIMITER $$

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID, NEW_VIP_LEVEL)
    VALUES(CURTIME(), "INSERT", NEW.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME, NEW.PESELID, NEW.VIP_LEVEL);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID)
    VALUES(CURTIME(), "DELETE", OLD.READER_ID);
END $$
DELIMITER ;

DELIMITER $$

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
FOR EACH ROW
BEGIN
	INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_FIRSTNAME, NEW_LASTNAME, NEW_PESELID, NEW_VIP_LEVEL,
    OLD_FIRSTNAME, OLD_LASTNAME, OLD_PESELID, OLD_VIL_LEVEL)
    VALUES(CURTIME(), "UPDATE",OLD.READER_ID, NEW.FIRSTNAME, NEW.LASTNAME,
    NEW.PESELID, NEW_VIP_LEVEL, OLD.FIRSTNAME, OLD.LASTNAME,
    OLD.PESELID, OLD_VIP_LEVEL);
END $$
DELIMITER ;
