EXPLAIN SELECT * FROM READERS
	WHERE FIRSTNAME = 'John';

CREATE INDEX READERSFNAME ON READERS (FIRSTNAME);
CREATE INDEX READERSLNAME ON READERS (LASTNAME);
CREATE INDEX BOOKSTITLE ON BOOKS (TITLE);

EXPLAIN SELECT * FROM READERS
	WHERE FIRSTNAME = 'John';