CREATE TABLE STATS (
	STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	STAT_DATE DATETIME NOT NULL,
	STAT VARCHAR(20) NOT NULL,
	VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS BESTSELLERS
FROM BOOKS BK
WHERE BK.BESTSELLER = 1;

USE TASK_CRUD;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS
	ON SCHEDULE EVERY 1 MINUTE
	DO
		BEGIN
			CALL UpdateBestsellers();
			INSERT INTO STATS (STAT_DATE, STAT, VALUE)
			VALUES (CURDATE(), 'BESTSELLERS', BESTSELLERS_COUNT.BESTSELLERS);
		END $$
DELIMITER ;